name: Run benchmarks

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

# Only trigger the benchmark job when you add `run benchmark` label to the PR
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run benchmark')
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install dependencies
        run: julia --color=yes -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1"'
      - name: Run benchmarks
        run: julia --color=yes -e 'using BenchmarkCI; BenchmarkCI.judge()'
      - name: Print judgement
        run: julia --color=yes -e 'using BenchmarkCI; BenchmarkCI.displayjudgement()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
